"""
Small official-case searcher.

The official_cases library is intentionally separate from the legacy LeCaRD /
CaseMatch database. It reads the curated JSONL generated by
scripts/import_official_cases.py and performs lightweight local retrieval.
"""

from __future__ import annotations

import json
import logging
import re
from pathlib import Path
from typing import Dict, List

import jieba

logger = logging.getLogger(__name__)


CASE_DOMAIN_KEYWORDS = {
    "婚姻": [
        "婚姻家庭",
        "离婚",
        "丈夫",
        "妻子",
        "配偶",
        "夫妻共同财产",
        "财产分割",
        "共同债务",
        "婚内财产",
        "房产分割",
        "离婚纠纷",
        "抚养权",
        "彩礼",
        "家庭暴力",
        "家暴",
        "反家庭暴力",
        "人身安全保护令",
        "保护令",
        "告诫书",
    ],
    "劳动": [
        "劳动争议",
        "劳动合同",
        "违法解除",
        "经济补偿",
        "赔偿金",
        "未签劳动合同",
        "工资",
        "社保",
        "劳动仲裁",
    ],
    "合同": [
        "合同纠纷",
        "买卖合同",
        "借款合同",
        "租赁合同",
        "违约责任",
        "合同解除",
        "合同效力",
    ],
    "侵权": [
        "侵权责任",
        "人身损害",
        "名誉权",
        "财产损害",
        "交通事故",
        "人格权",
        "未成年人侵权",
        "监护人责任",
        "家长赔偿",
        "人身损害赔偿",
        "教育机构责任",
        "学校责任",
        "校园伤害",
    ],
    "教育": [
        "学校责任",
        "教育机构责任",
        "校园伤害",
        "学生伤害",
        "教育管理职责",
    ],
    "知识产权": [
        "知识产权",
        "著作权",
        "商标",
        "专利",
        "技术秘密",
        "不正当竞争",
        "计算机软件",
    ],
    "公司": [
        "公司纠纷",
        "股东",
        "股权",
        "公司决议",
        "出资",
        "清算",
    ],
    "继承": [
        "继承",
        "遗嘱",
        "遗产",
        "法定继承",
        "遗赠",
    ],
    "刑事": [
        "刑事",
        "犯罪",
        "危险驾驶罪",
        "盗窃罪",
        "诈骗罪",
        "故意伤害罪",
        "故意伤害",
        "重伤",
        "轻伤",
        "刑事责任年龄",
        "未成年人犯罪",
        "未成年人",
        "校园伤害",
        "打架",
        "殴打",
    ],
    "行政": [
        "行政",
        "行政处罚",
        "行政复议",
        "行政诉讼",
        "行政许可",
        "行政程序",
        "告知申辩",
        "告知",
        "申辩",
        "申辩权",
    ],
    "治安": [
        "治安管理处罚",
        "殴打",
        "伤害",
        "报警",
        "公安机关",
        "派出所",
        "告诫书",
        "家庭暴力",
    ],
    "民事诉讼": [
        "人身安全保护令",
        "保护令",
        "申请保护令",
        "民事裁定",
        "诉前保护",
        "行为保全",
    ],
    "执行": [
        "执行",
        "强制执行",
        "执行异议",
        "案外人异议",
        "执行和解",
    ],
    "国家赔偿": [
        "国家赔偿",
        "刑事赔偿",
        "违法羁押",
        "赔偿决定",
        "赔偿义务机关",
    ],
}


DOMAIN_TO_CASE_CATEGORY = {
    "婚姻": "民事",
    "劳动": "民事",
    "合同": "民事",
    "侵权": "民事",
    "教育": "民事",
    "知识产权": "民事",
    "公司": "民事",
    "继承": "民事",
    "刑事": "刑事",
    "行政": "行政",
    "治安": "行政",
    "民事诉讼": "民事",
    "执行": "执行",
    "国家赔偿": "国家赔偿",
}


_QUERY_STOPWORDS = {
    "如何",
    "怎么",
    "怎么办",
    "是否",
    "可以",
    "应该",
    "哪些",
    "什么",
    "时候",
    "如果",
    "没有",
    "属于",
    "问题",
    "公司",
    "赔偿",
    "共同",
    "财产",
    "作出",
    "算不算",
    "行政机关",
    "行政",
    "机关",
    "处罚",
}

_BROAD_RELEVANCE_KEYWORDS = {
    "民事",
    "刑事",
    "行政",
    "执行",
    "犯罪",
    "赔偿金",
}

_FAMILY_VIOLENCE_PRIMARY_TERMS = [
    "家暴",
    "家庭暴力",
    "反家庭暴力",
    "丈夫",
    "妻子",
    "配偶",
    "婚姻",
    "离婚",
    "人身安全保护令",
    "保护令",
]

_FAMILY_VIOLENCE_STRONG_TERMS = [
    "家庭暴力",
    "家暴",
    "反家庭暴力",
    "人身安全保护令",
    "保护令",
    "告诫书",
    "婚姻家庭",
]

_POLICE_HANDLING_TERMS = ["报警", "公安", "公安机关", "派出所", "治安处罚", "治安管理处罚"]
_PROTECTION_ORDER_TERMS = ["人身安全保护令", "保护令", "申请保护令"]
_JUVENILE_AGE_TERMS = ["14岁", "15岁", "16岁", "不满16周岁", "未满16周岁", "不满十八周岁", "未成年", "未成年人", "少年"]
_FIGHTING_INJURY_TERMS = ["打架", "殴打", "伤害", "打伤", "重伤", "轻伤"]
_SCHOOL_CONTEXT_TERMS = ["在校", "学校", "同学", "学生", "校园"]
_JUVENILE_INJURY_STRONG_TERMS = [
    "故意伤害",
    "故意伤害罪",
    "重伤",
    "轻伤",
    "未成年人",
    "未成年人犯罪",
    "刑事责任年龄",
    "校园伤害",
    "学生伤害",
]
_CAMPUS_INJURY_STRONG_TERMS = [
    "未成年人",
    "未成年",
    "校园伤害",
    "学生伤害",
    "学校责任",
    "教育机构责任",
    "教育管理职责",
    "监护人责任",
    "家长赔偿",
]
_SELF_DEFENSE_QUERY_TERMS = ["正当防卫", "防卫", "反击", "被打", "被围殴", "被欺凌", "校园霸凌", "制止不法侵害"]
_SELF_DEFENSE_CASE_TERMS = ["正当防卫", "防卫过当", "制止不法侵害"]
_DANGEROUS_DRIVING_QUERY_TERMS = ["醉驾", "酒驾", "危险驾驶", "辅助驾驶", "自动驾驶", "机动车", "道路驾驶"]
_DANGEROUS_DRIVING_CASE_TERMS = ["危险驾驶", "危险驾驶罪", "醉酒驾驶", "辅助驾驶", "机动车", "道路驾驶"]


class OfficialCaseSearcher:
    """Searcher for the manually curated official_cases JSONL library."""

    source_name = "official_cases"

    def __init__(self, jsonl_path: str, top_k: int = 3):
        self.jsonl_path = Path(jsonl_path)
        self.top_k = top_k
        self._cases: list[dict] = []
        self._available = False
        self._load()

    @property
    def available(self) -> bool:
        return self._available

    def _load(self) -> None:
        if not self.jsonl_path.exists():
            logger.warning("官方精选案例库文件不存在: %s", self.jsonl_path)
            return
        cases = []
        try:
            with self.jsonl_path.open("r", encoding="utf-8") as f:
                for line_no, line in enumerate(f, 1):
                    line = line.strip()
                    if not line:
                        continue
                    try:
                        record = json.loads(line)
                    except json.JSONDecodeError as exc:
                        logger.warning("官方案例 JSONL 第 %d 行解析失败: %s", line_no, exc)
                        continue
                    if isinstance(record, dict) and record.get("case_id"):
                        cases.append(record)
            self._cases = cases
            self._available = bool(cases)
            logger.info("官方精选案例库已加载，共 %d 条", len(cases))
        except Exception as exc:
            logger.error("官方精选案例库加载失败: %s", exc)

    def get_available_domains(self) -> set:
        return {c.get("category", "").strip() for c in self._cases if c.get("category")}

    @staticmethod
    def _split_domains(domain: str | list | tuple | set) -> list[str]:
        if isinstance(domain, (list, tuple, set)):
            raw_parts = [str(item) for item in domain]
        else:
            raw_parts = re.split(r"[,，、/;；\s]+", str(domain or ""))
        domains = []
        for part in raw_parts:
            part = part.strip()
            if part and part not in domains:
                domains.append(part)
        return domains

    def _extract_core_issue_terms(self, query: str, primary_domain: str, secondary_domains: list[str]) -> list[str]:
        terms: list[str] = []
        seen = set()

        def add(term: str) -> None:
            if term and term not in seen:
                terms.append(term)
                seen.add(term)

        text = query or ""
        for keyword in CASE_DOMAIN_KEYWORDS.get(primary_domain, []):
            if keyword in text:
                add(keyword)
        if any(term in text for term in _FAMILY_VIOLENCE_PRIMARY_TERMS):
            for term in ["婚姻家庭"]:
                add(term)
        if "家暴" in text:
            for term in ["家暴", "家庭暴力", "反家庭暴力"]:
                add(term)
        if "家庭暴力" in text:
            for term in ["家庭暴力", "反家庭暴力"]:
                add(term)
        if any(term in text for term in _PROTECTION_ORDER_TERMS):
            for term in ["人身安全保护令", "保护令", "申请保护令"]:
                add(term)
        if any(term in text for term in _POLICE_HANDLING_TERMS):
            for term in ["报警", "公安机关", "派出所", "告诫书", "治安管理处罚"]:
                add(term)
        if any(term in text for term in _JUVENILE_AGE_TERMS):
            for term in ["未成年人", "刑事责任年龄", "未成年人犯罪"]:
                add(term)
        if any(term in text for term in _FIGHTING_INJURY_TERMS):
            for term in ["故意伤害", "故意伤害罪", "打架", "殴打"]:
                add(term)
        if "重伤" in text:
            add("重伤")
        if "轻伤" in text:
            add("轻伤")
        if any(term in text for term in _SCHOOL_CONTEXT_TERMS):
            for term in ["校园伤害", "学生伤害", "学校责任", "教育机构责任"]:
                add(term)
        if any(term in text for term in ["家长", "监护人", "赔偿"]):
            for term in ["监护人责任", "家长赔偿", "侵权责任", "人身损害赔偿"]:
                add(term)
        for domain in secondary_domains:
            for keyword in CASE_DOMAIN_KEYWORDS.get(domain, []):
                if keyword in text:
                    add(keyword)
        return terms

    def _analyze_case_query(self, query: str, domain: str | list | tuple | set = "") -> dict:
        domain_parts = self._split_domains(domain)
        query_text = query or ""

        primary_domain = ""
        secondary_domains = []
        special_topic = ""

        if any(term in query_text for term in _FAMILY_VIOLENCE_PRIMARY_TERMS):
            primary_domain = "婚姻"
            special_topic = "家庭暴力" if any(term in query_text for term in ["家暴", "家庭暴力", "人身安全保护令", "保护令"]) else ""
        elif (
            any(term in query_text for term in _JUVENILE_AGE_TERMS)
            and any(term in query_text for term in _FIGHTING_INJURY_TERMS)
            and any(term in query_text for term in ["刑事责任", "负刑事责任", "犯罪", "刑责"])
        ):
            primary_domain = "刑事"
            special_topic = "未成年人故意伤害 / 校园伤害"
        elif any(term in query_text for term in _SELF_DEFENSE_QUERY_TERMS):
            primary_domain = "刑事"
            special_topic = "正当防卫"
        else:
            for part in domain_parts:
                for key in CASE_DOMAIN_KEYWORDS:
                    if key in part:
                        primary_domain = key
                        break
                if primary_domain:
                    break
            if not primary_domain:
                text = f"{' '.join(domain_parts)} {query_text}"
                for key, keywords in CASE_DOMAIN_KEYWORDS.items():
                    if key in text or any(keyword in text for keyword in keywords):
                        primary_domain = key
                        break

        for part in domain_parts:
            for key in CASE_DOMAIN_KEYWORDS:
                if key in part and key != primary_domain and key not in secondary_domains:
                    secondary_domains.append(key)
        if any(term in query_text for term in _POLICE_HANDLING_TERMS) and "治安" != primary_domain and "治安" not in secondary_domains:
            secondary_domains.append("治安")
        if any(term in query_text for term in _PROTECTION_ORDER_TERMS) and "民事诉讼" != primary_domain and "民事诉讼" not in secondary_domains:
            secondary_domains.append("民事诉讼")
        if any(term in query_text for term in ["赔偿", "家长", "监护人"]) and "侵权" != primary_domain and "侵权" not in secondary_domains:
            secondary_domains.append("侵权")
        if any(term in query_text for term in _SCHOOL_CONTEXT_TERMS) and "教育" != primary_domain and "教育" not in secondary_domains:
            secondary_domains.append("教育")
        if any(term in query_text for term in ["赔偿", "家长赔偿", "民事赔偿"]) and "民事赔偿" not in secondary_domains:
            secondary_domains.append("民事赔偿")
        if not special_topic and any(term in query_text for term in _SCHOOL_CONTEXT_TERMS) and any(term in query_text for term in _FIGHTING_INJURY_TERMS):
            special_topic = "校园伤害 / 教育机构责任"

        core_issue_terms = self._extract_core_issue_terms(query_text, primary_domain, secondary_domains)
        return {
            "primary_domain": primary_domain,
            "secondary_domains": secondary_domains,
            "special_topic": special_topic,
            "core_issue_terms": core_issue_terms,
        }

    def _normalize_user_domain(self, query: str, domain: str = "") -> str:
        analysis = self._analyze_case_query(query, domain)
        return analysis["primary_domain"] or str(domain or "").strip()

    def _target_category(self, query: str, domain: str = "", primary_domain: str = "") -> str:
        user_domain = primary_domain or self._normalize_user_domain(query, domain)
        for key, category in DOMAIN_TO_CASE_CATEGORY.items():
            if key and key in user_domain:
                return category
        return ""

    def extract_legal_query_terms(self, query: str, user_domain: str = "") -> list[str]:
        """Extract legal-ish query terms and domain phrases for relevance filtering."""
        terms: list[str] = []
        seen = set()

        def add(term: str) -> None:
            term = term.strip()
            if len(term) >= 2 and term not in _QUERY_STOPWORDS and term not in seen:
                terms.append(term)
                seen.add(term)

        for keyword in CASE_DOMAIN_KEYWORDS.get(user_domain, []):
            if keyword in query:
                add(keyword)
        words = []
        for word in jieba.cut(query or ""):
            word = word.strip()
            if len(word) >= 2 and re.match(r"^[一-龥A-Za-z0-9]+$", word):
                words.append(word)
                add(word)

        # Recover common compound legal phrases that jieba may split.
        if "夫妻" in words and "共同财产" in words:
            add("夫妻共同财产")
        if ("财产" in words or "共同财产" in words) and ("分割" in words or "分配" in words):
            add("财产分割")
        if "劳动" in words and "合同" in words:
            add("劳动合同")
        if "危险" in words and "驾驶" in words:
            add("危险驾驶")
        if any(term in query for term in _JUVENILE_AGE_TERMS):
            add("未成年人")
            add("刑事责任年龄")
        if any(term in query for term in ["打架", "殴打", "打伤", "伤害"]):
            add("故意伤害")
        if "重伤" in query:
            add("重伤")
        if any(term in query for term in _SCHOOL_CONTEXT_TERMS):
            add("校园伤害")
            add("学生伤害")
        if any(term in query for term in ["家长", "监护人", "赔偿"]):
            add("监护人责任")
            add("家长赔偿")
        return terms

    def _case_text(self, case: dict) -> str:
        keywords = case.get("keywords")
        keywords_text = " ".join(keywords) if isinstance(keywords, list) else str(case.get("keywords_text", ""))
        return "\n".join(
            str(value or "")
            for value in (
                case.get("title", ""),
                case.get("category", ""),
                case.get("sub_category", ""),
                keywords_text,
                case.get("referee_points") or case.get("dispute_focus", ""),
                case.get("basic_facts") or case.get("case_summary", ""),
                case.get("judgment_reason") or case.get("court_reasoning", ""),
                case.get("judgment_result", ""),
            )
        )

    def is_case_relevant(
        self,
        case: dict,
        query: str,
        primary_domain: str,
        secondary_domains: list[str] | None = None,
        core_issue_terms: list[str] | None = None,
        special_topic: str = "",
    ) -> bool:
        case_text = self._case_text(case)
        secondary_domains = secondary_domains or []
        core_issue_terms = core_issue_terms or self._extract_core_issue_terms(query, primary_domain, secondary_domains)

        if any(term in case_text for term in _DANGEROUS_DRIVING_CASE_TERMS) and not any(
            term in query for term in _DANGEROUS_DRIVING_QUERY_TERMS
        ):
            return False
        if any(term in case_text for term in _SELF_DEFENSE_CASE_TERMS) and not any(
            term in query for term in _SELF_DEFENSE_QUERY_TERMS
        ):
            return False
        if any(term in case_text for term in _SELF_DEFENSE_CASE_TERMS) and any(
            term in query for term in _SELF_DEFENSE_QUERY_TERMS
        ):
            return True
        if any(term in case_text for term in _DANGEROUS_DRIVING_CASE_TERMS) and any(
            term in query for term in _DANGEROUS_DRIVING_QUERY_TERMS
        ):
            return True

        if special_topic == "正当防卫":
            return any(term in case_text for term in _SELF_DEFENSE_CASE_TERMS)
        if primary_domain == "婚姻" and special_topic == "家庭暴力":
            return any(term in case_text for term in _FAMILY_VIOLENCE_STRONG_TERMS)
        if primary_domain == "刑事" and special_topic == "未成年人故意伤害 / 校园伤害":
            return any(term in case_text for term in _JUVENILE_INJURY_STRONG_TERMS)
        if special_topic == "校园伤害 / 教育机构责任":
            return any(term in case_text for term in _CAMPUS_INJURY_STRONG_TERMS)

        strong_core_hit = any(
            term in case_text
            for term in core_issue_terms
            if (
                term not in _BROAD_RELEVANCE_KEYWORDS
                and term not in _POLICE_HANDLING_TERMS
                and term not in {"侵权责任", "人身损害赔偿", "赔偿金"}
            )
        )
        if strong_core_hit:
            return True

        expected_keywords = CASE_DOMAIN_KEYWORDS.get(primary_domain, [])
        domain_keyword_hit = any(
            keyword in case_text
            for keyword in expected_keywords
            if keyword not in _BROAD_RELEVANCE_KEYWORDS
        )
        query_terms = self.extract_legal_query_terms(query, primary_domain)
        query_hit = any(term in case_text for term in query_terms)
        if domain_keyword_hit and query_hit:
            return True

        sub_category = str(case.get("sub_category", ""))
        return any(
            keyword in sub_category
            for keyword in expected_keywords
            if keyword not in _BROAD_RELEVANCE_KEYWORDS
        )

    def _score_case(self, case: dict, terms: list[str], target_category: str) -> float:
        text = self._case_text(case)
        score = 0.0
        if target_category and case.get("category") == target_category:
            score += 8.0
        elif target_category:
            score -= 2.0
        keywords = set(case.get("keywords") or [])
        for term in terms:
            if term in keywords:
                score += 4.0
            if term and term in case.get("title", ""):
                score += 3.0
            if term and term in case.get("referee_points", ""):
                score += 2.5
            if term and term in text:
                score += 1.0
        return score

    @staticmethod
    def _truncate(text: str, max_len: int = 260) -> str:
        text = str(text or "").strip()
        if len(text) <= max_len:
            return text
        return text[:max_len].rstrip() + "..."

    def _format_result(self, case: dict) -> Dict:
        keywords = case.get("keywords") or []
        keywords_text = case.get("keywords_text") or "、".join(keywords)
        return {
            "case_id": case.get("case_id", ""),
            "official_case_no": case.get("official_case_no", ""),
            "title": case.get("title", ""),
            "case_level": case.get("case_level", "参考案例"),
            "category": case.get("category", ""),
            "sub_category": case.get("sub_category", ""),
            "legal_domain": case.get("category", ""),
            "keywords": keywords,
            "keywords_text": keywords_text,
            "judgment_date": case.get("judgment_date", ""),
            "case_number": case.get("case_number", ""),
            "court": case.get("court", ""),
            "referee_points": self._truncate(case.get("referee_points", ""), 320),
            "case_summary": self._truncate(case.get("basic_facts", ""), 220),
            "basic_facts": self._truncate(case.get("basic_facts", ""), 320),
            "judgment_result": self._truncate(case.get("judgment_result", ""), 220),
            "judgment_reason": self._truncate(case.get("judgment_reason", ""), 320),
            "court_reasoning": self._truncate(case.get("referee_points") or case.get("judgment_reason", ""), 320),
            "dispute_focus": self._truncate(case.get("referee_points", ""), 220),
            "source": case.get("source", "人民法院案例库 / 最高人民法院指导性案例"),
            "source_type": "official_case",
            "source_name": "official_cases",
            "source_url": case.get("source_url", ""),
        }

    def search(self, query: str, top_k: int = 3, domain: str = "") -> List[Dict]:
        if not self._available or not query:
            return []
        top_k = top_k or self.top_k
        analysis = self._analyze_case_query(query, domain)
        primary_domain = analysis["primary_domain"]
        terms = self.extract_legal_query_terms(query, primary_domain)
        terms = list(dict.fromkeys(terms + analysis["core_issue_terms"]))
        target_category = self._target_category(query, domain, primary_domain=primary_domain)
        scored = []
        candidates = [
            case for case in self._cases
            if not target_category or case.get("category") == target_category
        ]
        for case in candidates:
            if not self.is_case_relevant(
                case,
                query,
                primary_domain,
                secondary_domains=analysis["secondary_domains"],
                core_issue_terms=analysis["core_issue_terms"],
                special_topic=analysis["special_topic"],
            ):
                continue
            score = self._score_case(case, terms, target_category)
            if case.get("case_level") == "指导性案例":
                score += 0.5
            if score > 0 or not terms:
                scored.append((score, case))
        scored.sort(key=lambda item: item[0], reverse=True)
        if not scored:
            logger.info(
                "[官方案例检索] 未找到与 query/domain 高相关的参考案例 (primary=%s, secondary=%s, category=%s, core=%s)",
                primary_domain,
                analysis["secondary_domains"],
                target_category,
                analysis["core_issue_terms"],
            )
        return [self._format_result(case) for _, case in scored[:top_k]]

    def close(self) -> None:
        self._cases = []
        self._available = False
